### ISSUE TITLE
Configurable storage for Elasticsearch

### ISSUE THREAD

**Issue by ryane** [mantl/mantl#1199]
Currently, the Elasticsearch configuration is configured to write data on worker root volumes at /data. Ideally, this would be much more (easily) configurable than it is today.

We should research our options to provide production-ready elasticsearch storage configurations. And publish documentation on recommended configurations.

**Comment by siddharthist** [comment]
It would be great if the framework could detect the presence of Gluster/Ceph/whatever and use it when available.
