### ISSUE TITLE
document process for adding new nodes to existing clusters

### ISSUE THREAD

**Issue by ryane** [mantl/mantl#1216]
We should test and document the process to add new nodes of all types (control, worker, edge) to existing clusters on supported clouds. The terraform configurations for some cloud providers may need to be updated to support the process (for example, `count_offset` for node names like we have in openstack: https://github.com/CiscoCloud/mantl/blob/master/terraform/openstack/instance/main.tf#L6)

**Comment by distributorofpain** [comment]
Yes please, following this thread

**Comment by siddharthist** [comment]
As @distributorofpain said on #1337, this is what the process looks like for bare metal deployments:

> Add section for adding nodes
-update host file on deployment node or Add DNS entry to DNS server(s)
-ensure disk is setup same way on new node(s)
-Update Inventory file with new node(s)
-rerun deployment 
```
ansible-playbook -u centos -i inventory \
        -e provider=bare-metal \
        -e consul_dc=dc1 \
        -e docker-lvm-backed=true \
        -e docker_lvm_data_volume_size="80%FREE" \
        -e @security.yml  sample.yml >& bare-metal.log2
```

**Comment by siddharthist** [comment]
On #1434, @distributorofpain said that they were able to just run Ansible on that one new agent, so that's some good news on this front :smile:

**Comment by dcheperd** [comment]
I have implemented support for adding new Mantl Workers to existing Mantl clusters.

Please see  branch(#1585): https://github.com/CiscoCloud/mantl/tree/feature/single-worker

Instructions:
1. Provision your new node with terraform
2. The terraform.tfstate file should contain a single resource
3. Create a new file group_vars/all/vars.yml
4. Add the following variables to the file:
**hosts_core_override:** [
{"private_ipv4":"PRIVATEIP1","hostname":"mantl-control-03"},
{"private_ipv4":"PRIVATEIP2","hostname":"mantl-control-02"},
{"private_ipv4":"PRIVATEIP3","hostname":"mantl-control-01"} ]
**zookeeper_hosts_override:** ["mantl-control-03", "mantl-control-02", "mantl-control-01"]
**consul_servers_group_override:** ["PRIVATEIP1", "PRIVATEIP2", "PRIVATEIP3" ]

Where PRIVATEIP[1-N] is the private IP of the Mantl Control nodes.

5. Run ansible-playbook --private-key your-mantl-key mantl.yml
6. If the variables are correctly set in vars additional tasks and conditions will activate that correctly integrate a new Worker with an existing cluster.
