### ISSUE TITLE
WebSocket protocol does not work in Traefik (MANTL 1.0.3) 

### ISSUE THREAD

**Issue by mcapuccini** [mantl/mantl#1276]
Hi! I started a small MANTL 1.0.3 cluster on OpenStack. If I deploy applications, via Marathon, with the WebSocket entrypoint Traefik ignores them.  This is a problem for e.g. the Jupyter example https://github.com/CiscoCloud/mantl/tree/master/examples/jupyter. I deployed a MANTL 1.0.2 cluster on OpenStack, and there is no such problem. To reproduce the issue, please try the Jupyter example.

**Comment by stevendborrelli** [comment]
@mcapuccini what versions of traefik are being used? We just updated the package repos to use 1.0.0-beta.475.

**Comment by mcapuccini** [comment]
@stevendborrelli I was using the default version in 1.0.3. Now I rolled back my cluster to 1.0.2, as soon as I have the chance to test the new version I'll let you know.

**Comment by thomasvincent** [comment]
Traefik is on v1.3.0, so closing this out.
