### ISSUE TITLE
Calico support does not work on Mesos

### ISSUE THREAD

**Issue by lguminski** [mantl/mantl#1317]
Calico does not work in Mantl 1.0.3 as it does not attach to running container.

The reason for this that `calicoctl` utility from https://bintray.com/artifact/download/asteris/calico/calicoctl/calicoctl is of version `0.14.0`. The version does not start powerstrip automatically (as it used to do [in the past](https://github.com/projectcalico/calico-containers/blob/f00333b5f9e0d62eee211a35231300b76f43bcec/docs/getting-started/powerstrip/Demonstration.md)). So setting 

```
"DOCKER_HOST": "localhost:2377"
```

has no effect, because there is nothing listening at this port (#1266).

For this to work you need to use old version of `calicoctl` or simply upgrade docker to 1.9.0 (at least) which allows Calico intercept docker run commands without the need for powerstrip. The second option makes more sense. There is already an issue for this - #781

**Comment by siddharthist** [comment]
It's my impression that, at least from reading #1397, we use Docker 1.9 by default now. Does that fix this issue, @lguminski?

**Comment by ryane** [comment]
we are actually on 1.11.1 on master at this point.

**Comment by lguminski** [comment]
I encountered the problem on the latest (1.0.3) release. I will try to check master in the coming days, but unfortunately not now.

**Comment by anners** [comment]
I am having the same issue and I am on the most current version of Mantl. Should we be using a new version of calico?

**Comment by gwanii** [comment]
I got the same as above
```
$ nc 127.0.0.1 2377 
Ncat: Connection refused.
$ sudo docker images|awk '/calico/{print $1" "$2}'
calico/node v0.9.0
$ calicoctl version
0.14.0
```

**Comment by xiaods** [comment]
+1

**Comment by siddharthist** [comment]
@gwanii We use already use a Docker version later than 1.9. We also just improved Calico support with https://github.com/CiscoCloud/mantl/pull/1521. Has anyone seen this issue in a version later than that?

**Comment by siddharthist** [comment]
Ping @gwanii @lguminski

**Comment by Theaxiom** [comment]
This issue is stale.
