### ISSUE TITLE
ansible include_vars breaks variable precedence hierarchy

### ISSUE THREAD

**Issue by kbroughton** [mantl/mantl#1319]
I've noticed mantl often uses include_vars like so in elk/tasks/main.yml

```
 # Include mesos vars so that we can access the zk information in the json file
include_vars: "{{ playbook_dir }}/../roles/mesos/defaults/main.yml"
```

I've always considered this an ansible anti-pattern because you think defaults is lowest priority and will always be over-ridden. But when you use it in an include_vars, it clobbers [higher precedence variables](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) of the same name. 

The ways around it are
1. Duplicate default variable declarations in different roles/defaults/main.yml
   ( although it breaks DRY, it's not the works since these are supposed to be almost dummy variables)
2. Promote the required variables to a global defaults like group_vars/all
   ( you likely only need 2 or 3 vars from each of the included defaults/main.yml, probably the best solution)
3. Use the meta dependency of ansible
   ( gets a bit complicated with --start-at-task etc.)

Here are the current uses of include_vars

```
grep -RH include_vars ~/projects/mantl
mantl/addons/elk-uninstall.yml:    - include_vars: ../roles/elk/defaults/main.yml
mantl/playbooks/upgrade-0.5.1.yml:    - include_vars: ../roles/common/defaults/main.yml
mantl/playbooks/upgrade-consul.yml:    - include_vars: ../roles/consul/defaults/main.yml
mantl/playbooks/upgrade-mesos-marathon.yml:    - include_vars: ../roles/handlers/defaults/main.yml
mantl/playbooks/upgrade-mesos-marathon.yml:    - include_vars: ../roles/mesos/defaults/main.yml
mantl/playbooks/upgrade-mesos-marathon.yml:    - include_vars: ../roles/handlers/defaults/main.yml
mantl/playbooks/upgrade-mesos-marathon.yml:    - include_vars: ../roles/mesos/defaults/main.yml
mantl/playbooks/upgrade-mesos-marathon.yml:    - include_vars: ../roles/marathon/defaults/main.yml
mantl/roles/elk/tasks/main.yml:- include_vars: ../../marathon/defaults/main.yml
```
- Ansible version (NA): 
- Python version (NA):
- Git commit hash or branch: NA 
- Cloud Environment: NA
- Terraform version (NA):

**Comment by ryane** [comment]
we have a similar problem in #1308 where we need a cross-role variable (`zookeeper_server_group`). Ended up duplicating it for now but option 2. might ultimately be a better solution.

**Comment by siddharthist** [comment]
If we want to reuse variables from another role, can we just add it as a dependency? This will slow down our addons, but should keep all the proper precedence.
