### ISSUE TITLE
cli for interacting with mantl clusters

### ISSUE THREAD

**Issue by snoby** [mantl/mantl#1441]
The mesosphere platform provides a cli to interact with Marathon and Mesos.  It would be beneficial for some documentation or suggestions on how to get dcos_cli 
[https://github.com/dcos/dcos-cli](url)
To be configured against the mantl cluster.  Having a cli to launch apps and get status information would accelerate the user's of the mantl cluster.

Perhaps this is possible today, however I did not succeed in configuring the dcos_cli into interacting with the mantl cluster.

**Comment by Cryptophobia** [comment]
I do not see plans to do something like this. What is the dcos_cli? We would be replicating what people have done for kubectl and mesosphere and would be another piece that we have to maintain, right?

**Comment by snoby** [comment]
Yeah we can close this request.  I've been using kubernetes for a year now.  No longer using mantl.  it's dead and unsupported.

**Comment by Cryptophobia** [comment]
Which tool are you using to deploy kubernetes and what cloud provider are you running it on? Just wondering.

**Comment by thomasvincent** [comment]
https://github.com/kubernetes-incubator/kubespray <-- what I have working in my mantl fork
