### ISSUE TITLE
Non-root account removed from wheel group on Control and Kubeworkers

### ISSUE THREAD

**Issue by hpreston** [mantl/mantl#1467]
I typically use an account other than "root" to do installation and management of Mantl.  As of the current master branch, on the control and kubeworkers, my installation account is getting removed from "wheel".  This causes very interesting errors in installation (it works on some nodes, but not others), and then any future playbook to do anything fail as the account configured doesn't have sudo rights.  
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.6
- Git commit hash or branch:  latest Master as of May 16th or so
- Cloud Environment: vSphere
- Terraform version (`terraform version`): 0.6.16

**Comment by siddharthist** [comment]
@hpreston Can you add more information on how to reproduce this? How exactly do you do your installation as a non-root user? What do you change about the playbooks, and what failure messages do you see?

**Comment by siddharthist** [comment]
This might happen here:
https://github.com/CiscoCloud/mantl/blob/c747c15053caf3d1469ac9a0707e817a21a30ad5/roles/common/tasks/users.yml#L2-L10

**Comment by thomasvincent** [comment]
closing out due to lack of activity
