### ISSUE TITLE
mantl shipped support

### ISSUE THREAD

**Issue by ryane** [mantl/mantl#1590]
The following issues occur when deploying shipped to a default mantl installation:
- docker needs a manual restart to pick up network options.
- worker nodes require access to marathon. they are currently blocked by iptables.

anything else?

@stevendborrelli @mikejihbe

**Comment by angry-tony** [comment]
HI.. i'm new to mantl & shipped.. 
i am interested in "project shipped" and looking for how to deploy it.
is possible to deploy "project shipped UI" locally??
the only way is go to "https://ciscoshipped.io."??

**Comment by siddharthist** [comment]
@ryane How is shipped deployed? What needs to be done on the Mantl side w/r/t Docker?

**Comment by angry-tony** [comment]
@ryane "projec shipped" is opensource?? how can i install "shipped" for test??

**Comment by siddharthist** [comment]
@angry-tony We don't develop shipped. Take a look at it's website: https://ciscoshipped.io/

**Comment by stevendborrelli** [comment]
@angry-tony shipped is currently not open source, as it is a Cisco product that is deployed on top of mantl. Right now the main way to access is vis ciscoshipped.io, but talk to @fabgia  if you are looking to deploy it locally to your environment.

**Comment by angry-tony** [comment]
@stevendborrelli  wow.. good news..   one question... how to talk to @fabgia ?? could you give me his info??

**Comment by thomasvincent** [comment]
shipped has shutdown
