### ISSUE TITLE
Remove deprecated Openstack modules

### ISSUE THREAD

**Issue by siddharthist** [mantl/mantl#1658]
Looks like `terraform/openstack/hosts` and `terraform/openstack/hosts-floating` aren't used in the modularized TF configs, they should be removed. If people want to use them, they can check out an older version of the repo. 

``` bash
rm -r terraform/openstack/hosts
rm -r terraform/openstack/hosts-floating
```

should do it. 
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by shreab373** [comment]
hello, can i take this? i'm fairly new could you point me in the right direction?

**Comment by Cryptophobia** [comment]
@shreab373 : Hi, would you still like to work on this maintenance issue? 

For a start, you can fork mantl into your own github account. Create a feature branch naming it like `issue/1658-removing-old-terraform-modules` or something similar. Remove the modules from the branch and push your commit. Then you can come back here and create a pull request from your remote branch to our main master branch. Let me know if you have any questions.

**Comment by shreab373** [comment]
great! i'll get started, thanks :)

**Comment by shreab373** [comment]
@Cryptophobia why have you mentioned a list of requirements in the description?

**Comment by Cryptophobia** [comment]
@shreab373 : That is done automatically by our GitHub PR process. It adds a checklist for things we need to check for to make sure everything works cleanly before we merge the commits.
