### ISSUE TITLE
Do we run two instances of SkyDNS?

### ISSUE THREAD

**Issue by siddharthist** [mantl/mantl#1666]
Looks like there is a configuration for a skydns service in the etcd role:
- [roles/etcd/tasks/skydns.yml](https://github.com/CiscoCloud/mantl/blob/25a7e6c0b135ee99e9ca6037f8fad7e9cc44487d/roles/etcd/tasks/skydns.yml)
- [roles/etcd/templates/skydns.service.j2](https://github.com/CiscoCloud/mantl/blob/25a7e6c0b135ee99e9ca6037f8fad7e9cc44487d/roles/etcd/templates/skydns.service.j2)

And there's a pod definition in the K8s setup:
- [roles/kubernetes-addons/tasks/skydns.yml](https://github.com/CiscoCloud/mantl/blob/25a7e6c0b135ee99e9ca6037f8fad7e9cc44487d/roles/kubernetes-addons/tasks/skydns.yml)
- [roles/kubernetes-addons/templates/skydns-rc.yaml.j2](https://github.com/CiscoCloud/mantl/blob/25a7e6c0b135ee99e9ca6037f8fad7e9cc44487d/roles/kubernetes-addons/templates/skydns-rc.yaml.j2)

Looks like they depend on the same variable, `dns_setup` (in fact, the etcd one just checks that `dns_setup` is defined, not that it is true, which is probably buggy behavior). [`dns_setup` is set to `true`](https://github.com/CiscoCloud/mantl/blob/89b4662142822559fff23ecd94bff64661e94bf9/group_vars/all/kubernetes_vars.yml#L70) in our default installation.

[The etcd role is run on every node](https://github.com/CiscoCloud/mantl/blob/master/sample.yml#L29), while the k8s-addons are only a part of kubernetes. 

Why run two? Do etc and k8s have different configuration requirements? Could they be made to play nicely together? 
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by siddharthist** [comment]
@Zogg Do you know anything about this?

**Comment by siddharthist** [comment]
@Zogg Ping

**Comment by DanyC97** [comment]
@siddharthist i'm a bit curious - what does kubernetes-addons bring vs the default kubernetes which comes in the sample.yaml ?

I've deployed Mantl (from master) w/o having any addons role specified in the sample.yaml file hence my confusion

**Comment by siddharthist** [comment]
@DanyC97 Those addons were only added by mistake, and never should have been included, we never had a use case for them as a part of Mantl. They're removed from the most recent version of Mantl.

**Comment by DanyC97** [comment]
@siddharthist thanks for clarification
