### ISSUE TITLE
travis should ignore changes to .gitignore, .dockerignore, .mention-bot

### ISSUE THREAD

**Issue by siddharthist** [mantl/mantl#1705]
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by sehqlr** [comment]
Taking from a comment on a PR, we should ignore everything in the addons directory, also

**Comment by siddharthist** [comment]
This will be fixed in #1775

**Comment by Theaxiom** [comment]
This issue should now be resolved.
