### ISSUE TITLE
Release notes for 1.3

### ISSUE THREAD

**Issue by siddharthist** [mantl/mantl#1733]
This issue will keep track of things that must be noted in the release notes for 1.3. So far:
- Changed default for Mesos isolation: #1602 

Please add others in the comments!

**Comment by ryane** [comment]
* If you have an existing version of Mantl, make sure you update your local `mantl.yml` with the changes in `sample.yml`: #1634, #1667

**Comment by siddharthist** [comment]
* Updated AWS+k8s Terraform configuration

**Comment by ryane** [comment]
* update gce + k8s terraform configuration
* upgrading an existing cluster to take advantage of kubernetes cloud integration won't be straightfoward since it will require building new instances (to get the right IAM roles (aws) and service account scopes (gce)

**Comment by ryane** [comment]
Update a local mantl.yml from sample.yml if applicable. The order of node provisioning has changed. See #1751
