### ISSUE TITLE
CI build isn't skipping building forks

### ISSUE THREAD

**Issue by siddharthist** [mantl/mantl#1760]
See https://travis-ci.org/CiscoCloud/mantl/builds/146754048
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by sehqlr** [comment]
The code that I wrote to check for that is missing, probably from a bad merge. I'd like to get #1758 merged, then patch it
