### ISSUE TITLE
Expose docker when running in vagrant

### ISSUE THREAD

**Issue by TimWSpence** [mantl/mantl#1805]
Apologies if this is already possible. Could there be an option (see minikube docker-env for similar functionality) to expose the docker service running on eg the control node so that you can build docker images locally without running another instance of docker. Even better if it also ran a docker registry in the cluster to save having to push to a public registry in order to run containers in marathon/kubernetes

**Comment by ryane** [comment]
This is an interesting idea. It might just be a matter of setting the `docker_tcp` variable to true and then setting the appropriate env vars on the host machine. Turning on `docker_tcp_tls` might complicate things a bit since all of the certs now live on the mantl hosts.

**Comment by siddharthist** [comment]
@TimWSpence I'd definitely investigate turning on `docker_tcp`. Does that cover your use-case?

Maybe we can make a new issue for a private docker registry addon?

@ryane The certs were moved to the mantl hosts to support `docker_tcp_tls` (specifically, for Docker Swarm), so I sure hope it works :smile: `docker_tcp` should *never* be enabled without `docker_tcp_tls`.

**Comment by ryane** [comment]
@siddharthist I tend to agree and that's why this becomes more complicated. If I am understanding correctly, we would need to turn on `docker_tcp` and `docker_tcp_tls` and then set env variables like the following on the local host machine:

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.100.101:2375"
export DOCKER_CERT_PATH="/some/path/to/certs"
```

But since we no longer have the certificates on the local machine, we don't have anything we can use for `DOCKER_CERT_PATH`

**Comment by siddharthist** [comment]
@ryane Oh, I think I didn't understand the issue. Are we discussing building docker images on the host and running them on the guest? You're definitely correct, that's not currently possible.

**Comment by ryane** [comment]
yeah, just the ability to configure your local docker tools to talk to the docker daemon running in the vm. Things like docker-machine, minikube, etc. have support for doing this.

**Comment by siddharthist** [comment]
Yeah, then `docker_tcp` should work fine. We can investigate issuing a certificate for the provisioning machine to enable TLS auth (for both this and k8s), but that maintains the "golden laptop" issue where the provisioning machine has exclusive access to critical information about the cluster.

**Comment by TimWSpence** [comment]
@siddharthist @ryane How do we enable docker_tcp? Enabling that and dealing with the subsequent auth issues would definitely cover my use-case. I believe that's exactly how docker-machine and minikube do it.

@siddharthist I fully agree with the "golden laptop" comment for a remote cluster but in the context of a local vagrant environment as a one-stop development shop then it makes a lot of sense. I don't so much see a use-case for this in the more general case of a cloud-hosted cluster.

**Comment by ryane** [comment]
@TimWSpence https://github.com/CiscoCloud/mantl/blob/master/roles/docker/defaults/main.yml#L26

to test, you can just set that to `true` before doing vagrant up. There may or may not be some pain if you try to update an existing vagrant setup. I haven't tested this but you could try something like:

1. update the variable
2. run `vagrant rsync` 
3. `vagrant provision`

**Comment by ryane** [comment]
oh, and I just realized you will have to explicitly set `docker_tcp_tls` to false in this case since it is derived from `docker_tcp`
