### ISSUE TITLE
Configuring AWS template - concat error

### ISSUE THREAD

**Issue by hkuich** [mantl/mantl#1807]
Terraform 0.7 no longer uses "concat" to join strings (see: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#070-august-2-2016). 

When following the steps described in http://docs.mantl.io/en/latest/getting_started/aws.html, at the 

`terraform plan`

step, terraform crahes at terraform/aws/vpc/main.tf at line 31

`cidr_block = "${lookup(var.cidr_blocks, concat("az", count.index))}"`

This fixes it:

`cidr_block = "${lookup(var.cidr_blocks, "az${count.index}")}"`

I already have the fix in my fork, into which branch should I open a pull request?

**Comment by sehqlr** [comment]
@hkuich If you have a direct fix for this, you can make a PR into master.

**Comment by KaGeN101** [comment]
This seems to be fixed by #1808

AWS deploys 'without' issues, if this problem still there lets us know
