### ISSUE TITLE
vagrant builds fail with mesos package conflict

### ISSUE THREAD

**Issue by ryane** [mantl/mantl#1816]
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.12
- Git commit hash or branch: master
- Cloud Environment: vagrant
- Terraform version (`terraform version`): n/a

```
TASK: [mesos | install mesos packages] ****************************************
failed: [control-01] => (item=mesos-0.28.2,cyrus-sasl-md5) => {"changed": true, "item": "mesos-0.28.2,cyrus-sasl-md5", "rc": 1, "results": ["cyrus-sasl-md5-2.1.26-20.el7_2.x86_64 providing cyrus-sasl-md5 is already installed", "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.cogentco.com\n * epel: ca.mirror.babylon.network\n * extras: centos.mirror.constant.com\n * updates: mirror.metrocast.net\nResolving Dependencies\n--> Running transaction check\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n--> Processing Dependency: mesos = 0.25.0 for package: mesos-master-0.25.0-1.noarch\n--> Processing Dependency: mesos = 0.25.0 for package: mesos-agent-0.25.0-1.noarch\n---> Package mesos.x86_64 0:0.28.2-1 will be an update\n--> Processing Dependency: protobuf-devel for package: mesos-0.28.2-1.x86_64\n--> Processing Dependency: subversion-devel for package: mesos-0.28.2-1.x86_64\n--> Running transaction check\n---> Package mesos-agent.noarch 0:0.25.0-1 will be updated\n---> Package mesos-agent.noarch 0:1.0.0-1 will be an update\n--> Processing Dependency: mesos = 1.0.0 for package: mesos-agent-1.0.0-1.noarch\n---> Package mesos-master.noarch 0:0.25.0-1 will be updated\n---> Package mesos-master.noarch 0:1.0.0-1 will be an update\n---> Package protobuf-devel.x86_64 0:2.5.0-8.el7 will be installed\n--> Processing Dependency: protobuf-compiler = 2.
5.0-8.el7 for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: protobuf = 2.5.0-8.el7 for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Depen
dency: zlib-devel for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: libprotoc.so.8()(64bit) for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Process
ing Dependency: libprotobuf.so.8()(64bit) for package: protobuf-devel-2.5.0-8.el7.x86_64\n---> Package subversion-devel.x86_64 0:1.7.14-10.el7 will be installed\n--> Processing
 Dependency: subversion(x86-64) = 1.7.14-10.el7 for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Processing Dependency: apr-util-devel(x86-64) for package: subversion-de
vel-1.7.14-10.el7.x86_64\n--> Processing Dependency: apr-devel(x86-64) for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Running transaction check\n---> Package apr-devel
.x86_64 0:1.4.8-3.el7 will be installed\n---> Package apr-util-devel.x86_64 0:1.5.2-6.el7 will be installed\n--> Processing Dependency: openldap-devel(x86-64) for package: apr-
util-devel-1.5.2-6.el7.x86_64\n--> Processing Dependency: libdb-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n--> Processing Dependency: expat-devel(x86-64) for
 package: apr-util-devel-1.5.2-6.el7.x86_64\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n---> Package mesos.x86_
64 0:0.28.2-1 will be an update\n---> Package mesos.x86_64 0:1.0.0-3 will be an update\n---> Package protobuf.x86_64 0:2.5.0-8.el7 will be installed\n---> Package protobuf-comp
iler.x86_64 0:2.5.0-8.el7 will be installed\n---> Package subversion.x86_64 0:1.7.14-10.el7 will be installed\n---> Package zlib-devel.x86_64 0:1.2.7-15.el7 will be installed\n
--> Running transaction check\n---> Package expat-devel.x86_64 0:2.1.0-8.el7 will be installed\n---> Package libdb-devel.x86_64 0:5.3.21-19.el7 will be installed\n---> Package
openldap-devel.x86_64 0:2.4.40-9.el7_2 will be installed\n--> Processing Dependency: openldap(x86-64) = 2.4.40-9.el7_2 for package: openldap-devel-2.4.40-9.el7_2.x86_64\n--> Pr
ocessing Dependency: cyrus-sasl-devel(x86-64) for package: openldap-devel-2.4.40-9.el7_2.x86_64\n--> Running transaction check\n---> Package cyrus-sasl-devel.x86_64 0:2.1.26-20
.el7_2 will be installed\n---> Package openldap.x86_64 0:2.4.40-8.el7 will be updated\n---> Package openldap.x86_64 0:2.4.40-9.el7_2 will be an update\n--> Finished Dependency
Resolution\n\nDependencies Resolved\n\n================================================================================\n Package              Arch      Version              Re
pository            Size\n================================================================================\nInstalling for dependencies:\n apr-devel            x86_64    1.4.8-
3.el7          base                 188 k\n apr-util-devel       x86_64    1.5.2-6.el7          base                  76 k\n cyrus-sasl-devel     x86_64    2.1.26-20.el7_2
 updates              310 k\n expat-devel          x86_64    2.1.0-8.el7          base                  56 k\n libdb-devel          x86_64    5.3.21-19.el7        base
         38 k\n openldap-devel       x86_64    2.4.40-9.el7_2       updates              799 k\n protobuf             x86_64    2.5.0-8.el7          base                 338 k\
n protobuf-compiler    x86_64    2.5.0-8.el7          base                 261 k\n protobuf-devel       x86_64    2.5.0-8.el7          base                 163 k\n subversion
         x86_64    1.7.14-10.el7        base                 1.0 M\n subversion-devel     x86_64    1.7.14-10.el7        base                 288 k\n zlib-devel           x86_6
4    1.2.7-15.el7         base                  50 k\nUpdating for dependencies:\n mesos                x86_64    1.0.0-3              asteris-mantl-rpm     26 M\n mesos-agent
         noarch    1.0.0-1              asteris-mantl-rpm    3.1 k\n mesos-master         noarch    1.0.0-1              asteris-mantl-rpm    3.2 k\n openldap             x86_6
4    2.4.40-9.el7_2       updates              348 k\n\nTransaction Summary\n================================================================================\nInstall
   ( 12 Dependent packages)\nUpgrade             (  4 Dependent packages)\n\nTotal download size: 30 M\nDownloading packages:\nDelta RPMs disabled because /usr/bin/applydeltarp
m not installed.\n--------------------------------------------------------------------------------\nTotal                                               11 MB/s |  30 MB  00:02
    \nRunning transaction check\nRunning transaction test\n"]}
msg:

Transaction check error:
  file /usr/include/mesos/slave from install of mesos-1.0.0-3.x86_64 conflicts with file from package mesos-0.25.0-1.x86_64

Error Summary
-------------



FATAL: all hosts have already failed -- aborting
```

I'm not sure I understand why the mesos-1.0.0-3 package is even involved if we are explicitly installing 0.28.2.
- [ ] Fix package conflict (ping @Zogg)
- [ ] Update vagrant base image. The base image includes mesos 0.25. I am wondering if we should remove mesos from the base image. Right now, mesos-master and mesos-agent end up installed on all nodes and you end up with a lot of log spam b/c mesos-agent is trying and failing to run on control nodes and mesos-master is trying to run and failing on worker nodes. Right now, you have to manually disable the services accordingly.

---

For now, you can workaround the problem by removing mesos first early on during provisioning. For example, you can add this to the common playbook:

``` yaml
- name: remove mesos
  sudo: yes
  yum:
    name: mesos
    state: absent
```

**Comment by juliogomez** [comment]
What specific file would that common playbook be? Thanks!

**Comment by juliogomez** [comment]
Thanks for the hint, badarahmed. Unfortunately I am still getting the same error.

I edited roles/mesos/tasks/main.yml and added your lines at the beginning of the file. Then vagrant up and got the same result:

TASK: [mesos | install mesos packages] **************************************** 
failed: [control-01] => (item=mesos-0.28.2,cyrus-sasl-md5) => {"changed": true, "item": "mesos-0.28.2,cyrus-sasl-md5", "rc": 1, "results": ["cyrus-sasl-md5-2.1.26-20.el7_2.x86_64 providing cyrus-sasl-md5 is already installed", "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: sunsite.rediris.es\n * epel: ftp.cica.es\n * extras: sunsite.rediris.es\n * updates: sunsite.rediris.es\nResolving Dependencies\n--> Running transaction check\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n--> Processing Dependency: mesos = 0.25.0 for package: mesos-master-0.25.0-1.noarch\n--> Processing Dependency: mesos = 0.25.0 for package: mesos-agent-0.25.0-1.noarch\n---> Package mesos.x86_64 0:0.28.2-1 will be an update\n--> Processing Dependency: protobuf-devel for package: mesos-0.28.2-1.x86_64\n--> Processing Dependency: subversion-devel for package: mesos-0.28.2-1.x86_64\n--> Running transaction check\n---> Package mesos-agent.noarch 0:0.25.0-1 will be updated\n---> Package mesos-agent.noarch 0:1.0.0-1 will be an update\n--> Processing Dependency: mesos = 1.0.0 for package: mesos-agent-1.0.0-1.noarch\n---> Package mesos-master.noarch 0:0.25.0-1 will be updated\n---> Package mesos-master.noarch 0:1.0.0-1 will be an update\n---> Package protobuf-devel.x86_64 0:2.5.0-8.el7 will be installed\n--> Processing Dependency: protobuf-compiler = 2.5.0-8.el7 for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: protobuf = 2.5.0-8.el7 for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: zlib-devel for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: libprotoc.so.8()(64bit) for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: libprotobuf.so.8()(64bit) for package: protobuf-devel-2.5.0-8.el7.x86_64\n---> Package subversion-devel.x86_64 0:1.7.14-10.el7 will be installed\n--> Processing Dependency: subversion(x86-64) = 1.7.14-10.el7 for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Processing Dependency: apr-util-devel(x86-64) for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Processing Dependency: apr-devel(x86-64) for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Running transaction check\n---> Package apr-devel.x86_64 0:1.4.8-3.el7 will be installed\n---> Package apr-util-devel.x86_64 0:1.5.2-6.el7 will be installed\n--> Processing Dependency: openldap-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n--> Processing Dependency: libdb-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n--> Processing Dependency: expat-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n---> Package mesos.x86_64 0:0.28.2-1 will be an update\n---> Package mesos.x86_64 0:1.0.0-3 will be an update\n---> Package protobuf.x86_64 0:2.5.0-8.el7 will be installed\n---> Package protobuf-compiler.x86_64 0:2.5.0-8.el7 will be installed\n---> Package subversion.x86_64 0:1.7.14-10.el7 will be installed\n---> Package zlib-devel.x86_64 0:1.2.7-15.el7 will be installed\n--> Running transaction check\n---> Package expat-devel.x86_64 0:2.1.0-8.el7 will be installed\n---> Package libdb-devel.x86_64 0:5.3.21-19.el7 will be installed\n---> Package openldap-devel.x86_64 0:2.4.40-9.el7_2 will be installed\n--> Processing Dependency: openldap(x86-64) = 2.4.40-9.el7_2 for package: openldap-devel-2.4.40-9.el7_2.x86_64\n--> Processing Dependency: cyrus-sasl-devel(x86-64) for package: openldap-devel-2.4.40-9.el7_2.x86_64\n--> Running transaction check\n---> Package cyrus-sasl-devel.x86_64 0:2.1.26-20.el7_2 will be installed\n---> Package openldap.x86_64 0:2.4.40-8.el7 will be updated\n---> Package openldap.x86_64 0:2.4.40-9.el7_2 will be an update\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package              Arch      Version              Repository            Size\n================================================================================\nInstalling for dependencies:\n apr-devel            x86_64    1.4.8-3.el7          base                 188 k\n apr-util-devel       x86_64    1.5.2-6.el7          base                  76 k\n cyrus-sasl-devel     x86_64    2.1.26-20.el7_2      updates              310 k\n expat-devel          x86_64    2.1.0-8.el7          base                  56 k\n libdb-devel          x86_64    5.3.21-19.el7        base                  38 k\n openldap-devel       x86_64    2.4.40-9.el7_2       updates              799 k\n protobuf             x86_64    2.5.0-8.el7          base                 338 k\n protobuf-compiler    x86_64    2.5.0-8.el7          base                 261 k\n protobuf-devel       x86_64    2.5.0-8.el7          base                 163 k\n subversion           x86_64    1.7.14-10.el7        base                 1.0 M\n subversion-devel     x86_64    1.7.14-10.el7        base                 288 k\n zlib-devel           x86_64    1.2.7-15.el7         base                  50 k\nUpdating for dependencies:\n mesos                x86_64    1.0.0-3              asteris-mantl-rpm     26 M\n mesos-agent          noarch    1.0.0-1              asteris-mantl-rpm    3.1 k\n mesos-master         noarch    1.0.0-1              asteris-mantl-rpm    3.2 k\n openldap             x86_64    2.4.40-9.el7_2       updates              348 k\n\nTransaction Summary\n================================================================================\nInstall             ( 12 Dependent packages)\nUpgrade             (  4 Dependent packages)\n\nTotal size: 30 M\nDownloading packages:\nRunning transaction check\nRunning transaction test\n"]}
msg: 

Transaction check error:
  file /usr/include/mesos/slave from install of mesos-1.0.0-3.x86_64 conflicts with file from package mesos-0.25.0-1.x86_64

Error Summary
-------------



FATAL: all hosts have already failed -- aborting

**Comment by obsd-guru** [comment]
same here.. mesos-1.0.0-3.x86_64 conflicts with file from package mesos-0.25.0-1.x86_64

**Comment by landgazr** [comment]
I think I found what is causing the issue, but I don't know why it happens:

http://stackoverflow.com/questions/41590079/old-ansible-playbook-executes-everytime

It appears that it might have something to do with git, possibly perhaps the untracked cache which you can clear but I have not confirmed this. I had to make two changes in the code to get the vagrant run to complete.

But to make those changes, I had to fork the repo, make my changes, and clone. The changes involved removing the pre-installed mesos and changing the etcd version. For reference you can do a compare on [my fork](https://github.com/landgazr/mantl).

However, these are only workarounds for the time being of course.

**Comment by Theaxiom** [comment]
This should be resolved now.
