### ISSUE TITLE
kubectl exec fails on aws

### ISSUE THREAD

**Issue by ryane** [mantl/mantl#1821]
- Ansible version (`ansible --version`): 1.9.6
- Python version (`python --version`): 2.7.6
- Git commit hash or branch: master
- Cloud Environment: aws
- Terraform version (`terraform version`): v0.6.16

When running kubectl exec locally on AWS, you will see an error like the following:

```
$ kubectl --namespace=default exec -it nginx-3137573019-zuayi bash
Error from server: x509: certificate is valid for localhost, resching-aws-kubeworker-002, resching-aws-kubeworker-002.node.consul, ip-10-1-2-209, ip-10-1-2-209.node.consul, *.service.consul, kubernetes.default.svc.cluster.local, not ip-10-1-2-209.ec2.internal
```

Kubernetes derives the node names from the cloud provider and there is currently no way to override it (https://github.com/kubernetes/kubernetes/issues/22984). For now, we should probably add the internal EC2 private dns name to the certificate.

**Comment by siddharthist** [comment]
@ryane Is there a way to derive the cloud provider's DNS name as an Ansible variable?

**Comment by ryane** [comment]
@siddharthist I believe it is available as an ansible var on the first run before we change the hostname in the common role. after that, it will report the changed hostname. we might be able to preserve it from /etc/hostname before we change it and that might work across platforms. it is always available from the aws instance metadata but that is aws-specific, of course: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by Theaxiom** [comment]
This is fixed in https://github.com/mantl/mantl/commit/391181ba5b5370d46b5877a424c3290aaba9f709
