### ISSUE TITLE
LTS

### ISSUE THREAD

**Issue by snoby** [mantl/mantl#1827]
Are there any plans for a Long Term Support Release.

**Comment by snoby** [comment]
@johntdyer - Would be interested in this as well.

**Comment by thomasvincent** [comment]
@Theaxiom and I have plans for a LTS release. Just hammering down when, sooner than later though.

**Comment by Cryptophobia** [comment]
@Theaxiom @thomasvincent is the 2.0 first OSS release going to be first LTS or are we only just stabilizing the master branch at this point? We should plan a numbering strategy on the LTS releases (some even/odd decimals [2.2, 2.4] after the major version)?

**Comment by Theaxiom** [comment]
2.0 is just stabilizing master. After that, I think we are going to go with YY.MM.xx

**Comment by Cryptophobia** [comment]
@Theaxiom Okay, got it, kind of like Ubuntu number.

**Comment by Theaxiom** [comment]
Yeah, may other orgs are picking up that same strategy as well. I like it and I can easily tell when a release was released.

**Comment by Theaxiom** [comment]
We are supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor
