### ISSUE TITLE
mantl and rancher

### ISSUE THREAD

**Issue by wanghaisheng** [mantl/mantl#1837]
Anyone has heard rancher ，it seems promising too ,what is the difference between mantl and rancher?

**Comment by lowwalker** [comment]
Mantl is more a whole kitchen sink that provides a whole stack up/down for microservices. Rancher provides some of the same features that Mantl does but without the whole stack approach. For example, load balancing apps deployed in Rancher still require additional containers to be added as a service to a container. Mantl handles this automatically with it's all inclusive approach. 

Rancher would be best compared to as a replacement for Docker Swarm + Docker UCP. That's just from my perspective though.
