### ISSUE TITLE
Consul error 500 "No path to datacenter"

### ISSUE THREAD

**Issue by luzidl** [mantl/mantl#1840]
Hi,

I am setting up mantl on a vsphere 6 environment. My terraform works and I have a running cluster setup without any errors.

I am trying to install mantl now and the install always stops with an error 500. I found some reported issues that state, the consul_dc needs to be in lower case which is the case in my configuration.
The consul_dc name is also the same I am using with terraform!

So both resolutions I found did not solve the issue for me.

Anybody having the same issue and can help?

Thanks a mil!

---

TASK: [consul | create secure acl] *******************************************\* 
failed: [mantl-worker-003] => {"changed": true, "cmd": ["consul-cli", "acl-update", "--token=44c17508-7dea-4516-8866-20195b513696", "--name=Mantl Secure Token", "--rule=key:secure:write", "--rule=service::write", "fc4c332a-40cf-44b0-a729-1c1aaca16d01"], "delta": "0:00:00.009193", "end": "2016-10-04 17:22:17.610332", "rc": 1, "start": "2016-10-04 17:22:17.601139", "warnings": []}
stderr: Command "acl-update" is deprecated, Use acl update
Error: Unexpected response code: 500 (rpc error: No path to datacenter)
Usage:
  consul-cli acl-update <token> [flags]

Flags:
      --management[=false]: Create a management token
      --name="": Name of the ACL
      --rule=:

Global Flags:
      --auth=: The HTTP basic authentication username (and optional password) separated by a colon
      --consul="127.0.0.1:8500": Consul address:port
  -q, --quiet[=false]: Don't show usage on error
      --ssl[=false]: Use HTTPS when talking to Consul
      --ssl-ca-cert="": Path to a CA certificate file to validate the Consul server
      --ssl-cert="": Path to an SSL client certificate for authentication
      --ssl-key="": Path to an SSL client certificate key for authentication
      --ssl-verify[=true]: Verify certificates when connecting via SSL
      --token="": The Consul ACL token
      --token-file="": Path to file containing Consul ACL token

Unexpected response code: 500 (rpc error: No path to datacenter)

FATAL: all hosts have already failed -- aborting

---

**Changes to sample.yml:**

I set the consul_acl_datacenter to the name of my DC, all in lower case because of the upper case bug reported.
_consul_acl_datacenter: dc-aci-001_

*_Ansible version: *_
ansible 1.9.6

**Python** 2.7.5

**Cloud Env.:** vCenter/vSphere 6

**Terraform** **Version:** 0.7.4

**Comment by Theaxiom** [comment]
Unfortunately we have not been able to reproduce this so we are closing this issue. If you continue to experience issues please either comment here or open another issue, thanks!
