### ISSUE TITLE
Project Fork

### ISSUE THREAD

**Issue by andreimc** [mantl/mantl#1842]
I am just wondering if this project is still active?

**Comment by tomdavidson** [comment]
What makes you think it even *might* be dead?

https://github.com/CiscoCloud/mantl/commits/master
https://github.com/CiscoCloud/mantl/pulls
https://github.com/CiscoCloud/mantl/releases

**Comment by courtneyfaulkner** [comment]
@andreimc we've been wondering the same thing. All commit activity stopped Aug 16, right about the same time as the Cisco layoffs were announced: http://www.reuters.com/article/us-cisco-systems-layoffs-idUSKCN10S05D. I hope this product keeps moving somehow.

**Comment by stevendborrelli** [comment]
I can't speak for Cisco, but would folks be willing to contribute to a fork?

**Comment by lowwalker** [comment]
@stevendborrelli I definitely would.

**Comment by courtneyfaulkner** [comment]
I would too, time permitting.

**Comment by stevendborrelli** [comment]
Great! 

A while ago I had created the github org https://github.com/mantl, we might able to use it (if there are no trademark issues).

**Comment by badarahmed** [comment]
i'd be willing to contribute.

**Comment by axbaretto** [comment]
I definitely would.

**Comment by stevendborrelli** [comment]
I've changed the title of this issue.

**Comment by lowwalker** [comment]
We should see if we can get @siddharthist and @ryane to jump in as well. I'm one of the laid off cisco crew but I'll help admin the project as best I can @stevendborrelli

**Comment by siddharthist** [comment]
I'm in school now but I could review PRs for sure.

**Comment by ryane** [comment]
absolutely

**Comment by czuares** [comment]
I would be willing to contribute as well.

**Comment by tomdavidson** [comment]
The correlation with layoffs is more concerning then a month of little
activity. Thank your for pointing that out.

Willingness to invest (use and contributions) would depend on project
governance. Success of Mantl hinges on community.

Still seems early to fork. Lets hear from @brianhicks @ryane @siddharthist
and other contributors first.

**Comment by BrianHicks** [comment]
@tomdavidson makes a good point. For a fork to succeed, it needs a good governance model. This has the potential to become quite the bikeshed, though, so let's say that it's an outstanding question.

I would be in support of a fork, if the existing community requires it.

**Comment by andreimc** [comment]
@BrianHicks @stevendborrelli @siddharthist @lowwalker and the rest of the mantl supporters. Would be great if we could keep the project momentum going and form a community around it,  we are using mantl in production and would love to contribute to it. 

Would be great if someone still at Cisco could shed some light on the future of this project within their organisation or if it should be a community driven effort ?

**Comment by tomdavidson** [comment]
@andreimc  I agree that it would be nice to hear from Cisco on their intentions before the project is forked.

> or if it should be a community driven effort ?

 What is your hesitancy on a community driven effort?

**Comment by andreimc** [comment]
@tomdavidson I am not hesitant but I believe the people at Cisco were doing a great job driving this project.

Just trying to get a good understanding if they wish to continue doing so or not.

I believe that there is a great community around this and we can continue developing this and making it awesome :)

**Comment by distributorofpain** [comment]
So question... was Cisco directly driving this project or were they working with(or paying) Asteris?  Just trying to understand who exactly is behind the project and is controlling it.  

I am wondering if Cisco backed out because of Mesosphere basically incorporating most of the stated features mantl is trying to achieve ( not that they are there yet ).

**Comment by siddharthist** [comment]
@distributorofpain Cisco was paying Asteris to develop Mantl, but they aren't anymore. They also had some other folks working on it, but Asteris developers were definitely the driving force.

**Comment by tomdavidson** [comment]
@andreimc  thank you for elaborating, I was just checking. Businesses that have an open source product tend to dedicate much more time on the project than businesses that consume the product right? This is why I am slow to jump in on the project fork until there is a better understanding of what Cisco intends.

@distributorofpain Does it matter if Cisco had internal employees, contractors, community members developing Mantl? Cisco owns the copyright and marks.

Quite a few paas out there. I liked Mantl over DCOS because it seem to value "proudly seen elsewhere", cloud neutral,  and because of the selection of tech. I thought DCOS was quite a bit different.

**Comment by distributorofpain** [comment]
@tomdavidson oh, it doesn't matter to me in the overall scheme of things.  It was more of a question, so i could figure out if i might be able to entice my employer into providing some funding to a company working on the project, which is much easier than tracking down cisco employees.  He has some goals in mind and has hinted at being interested in investing funds to make them happen.  Me nor him wish to upset Cisco in the process though.  As you said, they own the copyrights and marks, so we don't want to stir the pot unnecessarily.

There may also be others who are willing to sponsor this project, i wouldn't want to exclude them either, but again, i wouldn't want to move on to that discussion until Cisco has provided some sort of blessing.  With that said, perhaps they keep their name on it, retain all rights and they throw some more logos up on the main page as bronze sponsors( no idea what they have invested in this so far )...

Hopefully, i havent stepped out of line with this.. if so feel free to edit ( and my apologies ).

On another note, i have a team of devs using mantl right now to host their app during the testing stages.  I have an employer who wants to bring a data center online with 200+ machines and Mantl as its core(openstack ironic for hardware control).  And finally, while not being a dev myself ( more like dev-ops ), i have no problem providing feedback and testing when feasible.

**Comment by stevendborrelli** [comment]
@distributorofpain we at Asteris would be happy to talk to you if you want to sponsor work on Mantl.

I've seen some public tweets from Cisco folks, and they are aware of this issue and are working on it.  I'm hoping to have more to say in the coming week or so.

**Comment by kenowens12** [comment]
Cisco recently acquired ContainerX; furthering our work with Container Infrastructure management and services. 
We’ve also been listening to the communities’ comments and feedback over the past few months, on themes such as:
 -          Better handling / Stewardship of PR’s
-          Packaging and automation questions.
-          Testbeds and test-driven processes.
-          Roadmaps and releases (PR / Community involvement).
 Due to this, we’ve taken a step back to look how Mantl best serves the community and needs of the users. We are currently looking at better ways to support the community for PR’s and testing. Better project stewardship, etc.
We’re also in talks with some exciting partners. So we ask that you bear with us for another few weeks while we determine the community direction in alignment with organizational priorities and community needs. Thank you for your continued interest and concerns.

**Comment by kenowens12** [comment]
@distributorofpain , would be happy to talk to you directly about your interests and support ideas. You can reach me at kenowens@cisco.com

**Comment by lowwalker** [comment]
The project is licensed with Apache2.0 so you _should_ be able to migrate to a GPLv3 without any trademarking issue. There's so many projects coming downstream though, it's like a firehose. It would be nice to see this project continue but if there's already been this much stagnation it's probably many features in the dust.

**Comment by distributorofpain** [comment]
I dont think that 2 months of "stagnation" is enough to leave this project in the dust.  Being that they seem to incorporate "coming of age" applications into the project, you are not going to see "bleeding edge" software thrown into this platform.  While some people might want to dabble in that, its a multifaceted system and it would suffer greatly should a bleeding edge component newly incorporated into the platform fail to perform at scale.  While outright maturity is not needed in a new component, there has to be some level of trust in said component to perform its function properly.

That said, i can see why Cisco went after ContainerX, one of the first supporting a windows docker container...  It also scales out and works cross platform.  I could see it being a mantl/mesos killer for those who primarily use mesos for docker containers...

**Comment by tomdavidson** [comment]
@kenowens12  awesome. Glad to hear Mantl still has Cisco's attention and looking forward to a public road map.

**Comment by gronau-it-cloud-computing** [comment]
we would sponsor the project !

**Comment by andreimc** [comment]
Hey guys, and update on this I had a chat with @kenowens12 on Oct 18.

```
We, Cisco, are trying to finalize this plan asap. Most of the technical leads want to continue to sponsor the project and support the community. I’ve even talked to CNCF about bringing the project to them. I’m pushing for an answer in the next week or 2.
 

If Cisco decides to not continue to support Mantl, I want to help the community in forking it.  It would be great to have your company propose CNCF incubation and I will be the sponsor on the technical committee. I am meeting with Steve from Asteris today to discuss the CNCF proposal process.
```

So we should be hearing back from them soon.

**Comment by zorel** [comment]
Hello. It's 3 weeks old now, any feedback?

**Comment by snakescott** [comment]
@andreimc any movement on this? almost four months since your October update.

**Comment by Zogg** [comment]
Indeed it is interesting to heard from @andreijs and @kenowens12, also @stevendborrelli, if there is any info to be shared?

**Comment by Theaxiom** [comment]
Hello everyone, Mantl is now a stand-alone FOSS project. Would any of you be interested in helping us get the engines started again? It would be greatly appreciated, thanks! We have a Mattermost channel setup here: https://mattermost.dynamictivity.com/signup_user_complete/?id=pjksr6h977n4zxxyto3ojp8twa

**Comment by thomasvincent** [comment]
Hey guys, you are about to see a ton of activity as I get Ansible moved up to 2.x .  I also plan to integrate weave and provide a high availability option. 
We need resources for CI/CD though. IF we are going to continue to support all these platforms. Especially the Cisco ones. We need accounts to do CI/CD. Any help would be appreciated.

**Comment by Cryptophobia** [comment]
@distributorofpain @gronau-it-cloud-computing : If any of you have mantl running and are still interested in supporting the future of this project, please reach out to me or any of the project maintainers. We are invested in this community and will be spending our time to bring new features to mantl!

**Comment by distributorofpain** [comment]
We switched to Mesosphere community ed. after we ran into dependency issues trying to rebuild our environment.  If there is a take away, its that downloading the dependencies for each version to one location and using that location to deploy from for new worker nodes or a redeploy, would be very helpful.  Mesosphere uses a docker image with theirs, very handy.

**Comment by Theaxiom** [comment]
@distributorofpain thanks for that tip, the plan is to create a Mantl container image which will act as the CM orchestrator for the cluster.
