### ISSUE TITLE
Terraform AWS IAM module fails with duplicate variable.

### ISSUE THREAD

**Issue by gordonfierce** [mantl/mantl#1845]
Attempting to use the AWS Terraform setup, `terraform get` fails with 

```
Error loading Terraform: module iam-profiles.root: 1 error(s) occurred:
* Variable 'short_name': duplicate found. Variable names must be unique.
```

mantl/terraform/aws/iam/control-profile.tf and mantl/terraform/aws/iam/worker-profile.tf both declare `variable "short_name" {default = "mantl"}`, which doesn't work with recent versions of Terraform. Similar issue discussed here: https://github.com/hashicorp/terraform/issues/8664
- Ansible version (`ansible --version`): ansible 1.9.2
- Python version (`python --version`): Python 2.7.10
- Git commit hash or branch: commit 3d1db1d78ef1d487f45102d2424ce62a6e934855 master
- Cloud Environment: AWS
- Terraform version (`terraform version`): Terraform v0.7.6

**Comment by lowwalker** [comment]
@gordonfierce I think you need to pull those vars from the two profiles, and then put that var into a file in the same dir in a file named common.tf

**Comment by kbroughton** [comment]
That fixed it thanks.  This should be pushed to master.

**Comment by KaGeN101** [comment]
Closing this as not seeing on current build mantl-contol-xxx vs manl-worker-xxx and mantl-kubeworker-xxx is all unique now. Also it all comes from aws.tf now and not separate tf file anymore

Let us know if you still experience this
