### ISSUE TITLE
TASK: [mesos | install mesos packages] fails

### ISSUE THREAD

**Issue by alma-bm** [mantl/mantl#1855]
hi
trying mantl .. when doing a "vagrant up" after a while i get this error message.

TASK: [mesos | install mesos packages] ****************************************
failed: [control-01] => (item=mesos-0.28.2,cyrus-sasl-md5) => {"changed": true, "item": "mesos-0.28.2,cyrus-sasl-md5", "rc": 1, "results": ["cyrus-sasl-md5-2.1.26-20.el7_2.x86_64 providing cyrus-sasl-md5 is already installed", "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: ftp.hosteurope.de\n * epel: mirror.daniel-jost.net\n * extras: ftp-stud.fht-esslingen.de\n * updates: centos.mirrors.as250.net\nResolving Dependencies\n--> Running transaction check\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n--> Processing Dependency: mesos = 0.25.0 for package: mesos-master-0.25.0-1.noarch\n--> Processing Dependency: mesos = 0.25.0 for package: mesos-agent-0.25.0-1.noarch\n---> Package mesos.x86_64 0:0.28.2-1 will be an update\n--> Processing Dependency: protobuf-devel for package: mesos-0.28.2-1.x86_64\n--> Processing Dependency: subversion-devel for package: mesos-0.28.2-1.x86_64\n--> Running transaction check\n---> Package mesos-agent.noarch 0:0.25.0-1 will be updated\n---> Package mesos-agent.noarch 0:1.0.0-1 will be an update\n--> Processing Dependency: mesos = 1.0.0 for package: mesos-agent-1.0.0-1.noarch\n---> Package mesos-master.noarch 0:0.25.0-1 will be updated\n---> Package mesos-master.noarch 0:1.0.0-1 will be an update\n---> Package protobuf-devel.x86_64 0:2.5.0-8.el7 will be installed\n--> Processing Dependency: protobuf-compiler = 2.5.0-8.el7 for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: protobuf = 2.5.0-8.el7 for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: zlib-devel for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: libprotoc.so.8()(64bit) for package: protobuf-devel-2.5.0-8.el7.x86_64\n--> Processing Dependency: libprotobuf.so.8()(64bit) for package: protobuf-devel-2.5.0-8.el7.x86_64\n---> Package subversion-devel.x86_64 0:1.7.14-10.el7 will be installed\n--> Processing Dependency: subversion(x86-64) = 1.7.14-10.el7 for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Processing Dependency: apr-util-devel(x86-64) for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Processing Dependency: apr-devel(x86-64) for package: subversion-devel-1.7.14-10.el7.x86_64\n--> Running transaction check\n---> Package apr-devel.x86_64 0:1.4.8-3.el7 will be installed\n---> Package apr-util-devel.x86_64 0:1.5.2-6.el7 will be installed\n--> Processing Dependency: openldap-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n--> Processing Dependency: libdb-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n--> Processing Dependency: expat-devel(x86-64) for package: apr-util-devel-1.5.2-6.el7.x86_64\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n---> Package mesos.x86_64 0:0.25.0-1 will be updated\n---> Package mesos.x86_64 0:0.28.2-1 will be an update\n---> Package mesos.x86_64 0:1.0.0-3 will be an update\n---> Package protobuf.x86_64 0:2.5.0-8.el7 will be installed\n---> Package protobuf-compiler.x86_64 0:2.5.0-8.el7 will be installed\n---> Package subversion.x86_64 0:1.7.14-10.el7 will be installed\n---> Package zlib-devel.x86_64 0:1.2.7-15.el7 will be installed\n--> Running transaction check\n---> Package expat-devel.x86_64 0:2.1.0-8.el7 will be installed\n---> Package libdb-devel.x86_64 0:5.3.21-19.el7 will be installed\n---> Package openldap-devel.x86_64 0:2.4.40-9.el7_2 will be installed\n--> Processing Dependency: openldap(x86-64) = 2.4.40-9.el7_2 for package: openldap-devel-2.4.40-9.el7_2.x86_64\n--> Processing Dependency: cyrus-sasl-devel(x86-64) for package: openldap-devel-2.4.40-9.el7_2.x86_64\n--> Running transaction check\n---> Package cyrus-sasl-devel.x86_64 0:2.1.26-20.el7_2 will be installed\n---> Package openldap.x86_64 0:2.4.40-8.el7 will be updated\n---> Package openldap.x86_64 0:2.4.40-9.el7_2 will be an update\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package              Arch      Version              Repository            Size\n================================================================================\nInstalling for dependencies:\n apr-devel            x86_64    1.4.8-3.el7          base                 188 k\n apr-util-devel       x86_64    1.5.2-6.el7          base                  76 k\n cyrus-sasl-devel     x86_64    2.1.26-20.el7_2      updates              310 k\n expat-devel          x86_64    2.1.0-8.el7          base                  56 k\n libdb-devel          x86_64    5.3.21-19.el7        base                  38 k\n openldap-devel       x86_64    2.4.40-9.el7_2       updates              799 k\n protobuf             x86_64    2.5.0-8.el7          base                 338 k\n protobuf-compiler    x86_64    2.5.0-8.el7          base                 261 k\n protobuf-devel       x86_64    2.5.0-8.el7          base                 163 k\n subversion           x86_64    1.7.14-10.el7        base                 1.0 M\n subversion-devel     x86_64    1.7.14-10.el7        base                 288 k\n zlib-devel           x86_64    1.2.7-15.el7         base                  50 k\nUpdating for dependencies:\n mesos                x86_64    1.0.0-3              asteris-mantl-rpm     26 M\n mesos-agent          noarch    1.0.0-1              asteris-mantl-rpm    3.1 k\n mesos-master         noarch    1.0.0-1              asteris-mantl-rpm    3.2 k\n openldap             x86_64    2.4.40-9.el7_2       updates              348 k\n\nTransaction Summary\n================================================================================\nInstall             ( 12 Dependent packages)\nUpgrade             (  4 Dependent packages)\n\nTotal download size: 30 M\nDownloading packages:\nDelta RPMs disabled because /usr/bin/applydeltarpm not installed.\n--------------------------------------------------------------------------------\nTotal                                              232 kB/s |  30 MB  02:12     \nRunning transaction check\nRunning transaction test\n"]}
msg:

Transaction check error:
  file /usr/include/mesos/slave from install of mesos-1.0.0-3.x86_64 conflicts with file from package mesos-0.25.0-1.x86_64

Error Summary
-------------

FATAL: all hosts have already failed -- aborting

**Comment by roicostas** [comment]
I have encountered the same problem. There are a couple of solutions:

1. you may ssh your virtual machines (mesos master and mesos slaves) and uninstall mesos-0.25.0-1.x86_64, then provision them again (run vagrant provision)

2. You can edit mesos role on ansible and uninstall mesos before installing it. This is just adding at the beginning of files roles/mesos/tasks/leader.yml, roles/mesos/tasks/follower.yml and roles/mesos/tasks/main.yml the following:
```
---
- name: remove current mesos
  sudo: yes
  yum:
    name: mesos
    state: removed
```

**Comment by landgazr** [comment]
There is one caveat to your second workaround. Check out my comment [here](https://github.com/mantl/mantl/issues/1816#issuecomment-283763109).

**Comment by Theaxiom** [comment]
This should be resolved now.
