### ISSUE TITLE
Mantl.io down?

### ISSUE THREAD

**Issue by ammaskartik** [mantl/mantl#1862]
We are thinking of digging into Mantl but it looks like mantl.io is down, I get a Whoops, looks like something went wrong. 

Just making sure this is being worked on and is still an actively maintained project, it looks promising. 

Thanks.

**Comment by stevendborrelli** [comment]
This is a known issue, we are working on it. We hope to have the site up again soon!

**Comment by ammaskartik** [comment]
Thank you for the quick response on that.
