### ISSUE TITLE
mantl.io down

### ISSUE THREAD

**Issue by ronaldpetty** [mantl/mantl#1863]
Hello,

It seems the mantl.io site is down (since last week for me.)  Is it coming back?

Ron

**Comment by stevendborrelli** [comment]
Sorry about that. We are aware of the issue and responsible party (who owns the DNS entry) is working on it.

**Comment by ronaldpetty** [comment]
Thanks Steven, docs.mantl.io is working so I am good for now!

**Comment by ronaldpetty** [comment]
Site is back.
