### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by aktarali** [mantl/mantl#1868]
Hi,

If I'm running kubernetes on mesos and i Wanted to use ceph, which layer should i configure ceph on? Mesos or k8s?

I know the question might not be directly related, just looking for guidance.

Thanks
Ali.

**Comment by stevendborrelli** [comment]
I don't know the current state of Kubernetes support on Mesos, but I'd suggest running Kubernetes standalone, as it will be better supported and easier to debug. 

As for Ceph, I'd look to see which platform has better support for running it.
