### ISSUE TITLE
Ebert Support

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1874]
Consider adding Ebert badge to identify code smells. 

Example:
https://ebertapp.io/github/thomasvincent/mantl

Project should open its own account.

**Comment by Cryptophobia** [comment]
Another choice also is codeclimate. It's free for open source projects.

**Comment by Theaxiom** [comment]
I also have many CI tools in my cloud infrastructure, I wouldn't mind hosting some tools for Mantl if needed.

**Comment by thomasvincent** [comment]
For the time being we may have to go that route.

**Comment by Theaxiom** [comment]
I know of quite a few projects that use codeclimate.

**Comment by thomasvincent** [comment]
code climate works.

**Comment by Theaxiom** [comment]
I think this can wait for 2.1, since most of our stuff is Ansible

**Comment by Theaxiom** [comment]
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor
