### ISSUE TITLE
Get new travis account setup

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1875]
From what i can see Travis is not configured for this repo. it would be very helpful to have CI going again.

**Comment by Theaxiom** [comment]
Yeah, I was thinking that earlier. I need to do some digging because Travis can only point to the same repo 1 across all Travis accounts. I am sure someone already has it configured, so I need to get access.

**Comment by Theaxiom** [comment]
CI is an absolute must. 👍

**Comment by thomasvincent** [comment]
Not sure it is setup. 
https://travis-ci.org/mantl/mantl

**Comment by Theaxiom** [comment]
Ok, I just sent a request for authorization for Travis to access mantl. Only the mantl owners can approve that.

**Comment by thomasvincent** [comment]
ok, i have a https://travis-ci.org/thomasvincent/mantl going on my branch

**Comment by Theaxiom** [comment]
Thanks 👍

**Comment by Theaxiom** [comment]
Alright we have Travis setup: https://travis-ci.org/mantl/mantl

**Comment by Theaxiom** [comment]
I've added the badge to the README, it appears that we have a lot of work to do! :D
