### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1877]
I would suggest using the project function to talk communicate a roadmap

**Comment by Theaxiom** [comment]
Thank you, that is a great idea.

**Comment by Cryptophobia** [comment]
Yes, great idea! The scope of the project is pretty large so we should think about short term vs. long term contributions and improvements.

**Comment by Theaxiom** [comment]
@Cryptophobia would you mind joining the ChatOps server @ https://mattermost.dynamictivity.com/signup_user_complete/?id=pjksr6h977n4zxxyto3ojp8twa that way we can communicate better and in realtime? 👍

**Comment by Theaxiom** [comment]
FYI @Cryptophobia here's why I prefer Mattermost over any SAAS ChatOps: https://www.mattermost.org/why-we-made-mattermost-an-open-source-slack-alternative/

I am a huge FOSS advocate and I will prefer it whenever and wherever I can. That being said, I do have a very open mind and would like to discuss the PROs and CONs of switching to Slack or Gitter. Being that I already had Mattermost setup (as well as an Open Source projects team for other Open Source projects I maintain), it only took me a second to create a channel.

The current Gitter account for Mantl is branded as CiscoCloud, so for now I would prefer not to use that existing setup. Here's the invite link for Mattermost: https://mattermost.dynamictivity.com/signup_user_complete/?id=pjksr6h977n4zxxyto3ojp8twa

I do have it on my backlog to setup oAuth integration with GitHub for my GitLab instance to make it seamless for people to register, I just have not done it yet. I suppose I can get to it over the weekend.

I look forward to speaking with you in realtime and I really appreciate your help and initiative with this project, let's get this thing launched! :)

**Comment by Theaxiom** [comment]
I like how Flarum has laid our their roadmap in a GitHub issue: https://github.com/flarum/core/issues/74

**Comment by Cryptophobia** [comment]
@Theaxiom Laying out the roadmap in a GitHub issue also helps people check out the features that they might be opening an issue about so I like this approach.

**Comment by Theaxiom** [comment]
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor
