### ISSUE TITLE
Merge in good changes from forks

### ISSUE THREAD

**Issue by Theaxiom** [mantl/mantl#1899]
There are quite a few forks which have a cumulative commit count of 100+, we should see if we can bring some of that work into mantl.

- https://github.com/waldophotos/mantl
- https://github.com/datascienceinc/mantl
- https://github.com/CognitiveScale/mantl
- https://github.com/supernova106/mantl

**Comment by Theaxiom** [comment]
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor

**Comment by davedittrich** [comment]
Is there continued development on endeavor active? I am interested in generalizing the security-setup script to be more modular, but want to ensure contributions (PRs) will be considered.  Thanks.

**Comment by Cryptophobia** [comment]
@Theaxiom Travis?

**Comment by Theaxiom** [comment]
We haven't yet started development on Endeavor, it is still up for RFC. We are considering starting with the base platform of Rancher 1.6 -- you can participate in the RFC discussion here: https://github.com/cloud-endeavor/endeavor/issues/1
