### ISSUE TITLE
Error creating DNS RecordSet: googleapi: Error 404: Failed to find project <project-number>, notFound

### ISSUE THREAD

**Issue by kbroughton** [mantl/mantl#1920]
> terraform apply
fails with
* google_dns_record_set.dns-edge: Error creating DNS RecordSet: googleapi: Error 404: Failed to find project <123***567>, notFound

according to docs i set project as
provider "google" {
  credentials = "${file("/path/to/account.json")}"
  project = "number version of project"
  region = "us-central1"
}

but this requires that I fix terraform/gce/dns/main.tf b/terraform/gce/dns/main.tf
by adding project = <project name>
to resource "google_dns_record_set"

$ git log -n 1
commit 9b0fd0fbf7951f525477599196c46e6311e8f478
Merge: b8aea818 2051383c
Author: Thomas Vincent <thomasvincent@gmail.com>
Date:   Mon Apr 17 19:38:47 2017 -0700
 $ terraform --version
Terraform v0.8.8

**Comment by Theaxiom** [comment]
Fixed with merge of #1921
