### ISSUE TITLE
AWS EC2 host dns names not included in keys generated

### ISSUE THREAD

**Issue by KaGeN101** [mantl/mantl#1937]
During terraforming the keys generated des not include the ec2.internal host name.

This causes a lot of weird things to hapen on kubernetes services.

Forcing the names into the roles/certificates/defaults file fixes the issue and k8 serviecs then behave
roles/certificates/defaults/main.yml
 ```
dns:
   - "{{ inventory_hostname }}"
   - "{{ inventory_hostname }}.node.consul"
+  - "{{ inventory_hostname }}.ec2.internal"
   - "{{ ansible_hostname }}"
   - "{{ ansible_hostname }}.node.consul"
+  - "{{ ansible_hostname }}.ec2.internal"
   - "*.service.consul"
   - "kubernetes.default.svc.{{ cluster_name }}"
```

These must either be included on an AWS deploy or the AWS hots names cannot be ec2.internal and must be forced to node.consul

The error for all nodes when using any kubectl service like logs is this, boldhighlights the problem:
Error from server: Get https://ip-10-1-3-159.ec2.internal:10250/containerLogs/kube-system/kube-proxy-ip-10-1-3-159.ec2.internal/kube-proxy: x509: certificate is valid for localhost, mantl-control-03, mantl-control-03.node.consul, ip-10-1-3-159, **ip-10-1-3-159.node.consul**, *.service.consul, kubernetes.default.svc.cluster.local, not **ip-10-1-3-159.ec2.internal**

- sample.yaml:  none
- aws.tf: no changes except hooks
- Ansible version (`ansible --version`): ansible 1.9.6
- Python version (`python --version`): Python 2.7.12
- Git commit hash or branch: f04d06ded13bfcd6b57600a0ee5e5f28cede5e15
- Cloud Environment: AWS
- Terraform version (`terraform version`): Terraform v0.9.3

**Comment by joesenova** [comment]
From my point of view there should be a configurable config with a list of cloud platforms host dns names that are enabled in the setup of Mantl.

That list will then be used when creating all the keys required for the kube worker nodes

**Comment by joesenova** [comment]
Related/Duplicate issue:: https://github.com/mantl/mantl/issues/1821

**Comment by Theaxiom** [comment]
This is fixed by https://github.com/mantl/mantl/commit/391181ba5b5370d46b5877a424c3290aaba9f709
