### ISSUE TITLE
k8 network overlay and as such DNS not coming up

### ISSUE THREAD

**Issue by KaGeN101** [mantl/mantl#1942]
There seems to be a known race key issue where somehow the DNS and as such the network overlay does not behave as expected. As per here and here:

https://github.com/kubernetes/kubernetes/issues/19332
https://github.com/kubernetes/kubernetes/issues/10265#issuecomment-117267504

kubectl logs kube-dns-v8-7yujb kube2sky
I0421 17:26:13.289951       1 kube2sky.go:383] [Attempt: 1] Attempting access to etcd after 5 second sleep
I0421 17:26:18.290197       1 kube2sky.go:383] [Attempt: 2] Attempting access to etcd after 5 second sleep
I0421 17:26:23.290332       1 kube2sky.go:383] [Attempt: 3] Attempting access to etcd after 5 second sleep
I0421 17:26:28.290583       1 kube2sky.go:383] [Attempt: 4] Attempting access to etcd after 5 second sleep
I0421 17:26:33.290722       1 kube2sky.go:383] [Attempt: 5] Attempting access to etcd after 5 second sleep
I0421 17:26:38.290979       1 kube2sky.go:383] [Attempt: 6] Attempting access to etcd after 5 second sleep
I0421 17:26:43.291182       1 kube2sky.go:383] [Attempt: 7] Attempting access to etcd after 5 second sleep
I0421 17:26:48.291392       1 kube2sky.go:383] [Attempt: 8] Attempting access to etcd after 5 second sleep
I0421 17:26:53.291621       1 kube2sky.go:383] [Attempt: 9] Attempting access to etcd after 5 second sleep
[centos@mantl-control-01 ~]$ kubectl logs kube-dns-v8-7yujb kube2sky

kube2sky.go:389] Etcd server found: http://10.1.2.24:2379
I0422 21:10:35.660653       1 kube2sky.go:455] Using https://10.254.0.1:443 for kubernetes master
I0422 21:10:35.660673       1 kube2sky.go:456] Using kubernetes API 
E0422 21:11:05.661454       1 reflector.go:136] Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints: dial tcp 10.254.0.1:443: i/o timeout
E0422 21:11:05.661633       1 reflector.go:136] Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services: dial tcp 10.254.0.1:443: i/o timeout

- sample.yaml - None
- Ansible version (`ansible --version`): ansible 1.9.6
- Python version (`python --version`): Python 2.7.12
- Git commit hash or branch: f04d06ded13bfcd6b57600a0ee5e5f28cede5e15
- Cloud Environment: AWS
- Terraform version (`terraform version`): Terraform v0.9.3

**Comment by Theaxiom** [comment]
I can think of a few potential solutions:
- Delete the token and see if it works
- Update kube2sky (This should probably happen anyway)
- Update hyperkube (This needs to happen anyway)

**Comment by Theaxiom** [comment]
Try changing the hyperkube to one of these more recent images and see what happens: https://console.cloud.google.com/gcr/images/google-containers/global/hyperkube-amd64?project=google-containers

**Comment by KaGeN101** [comment]
I have checked the keys multiple times now does not seem like that is the issue think it is related to #1944. Going to change their interfaces and see what happens

**Comment by KaGeN101** [comment]
#1945

**Comment by dissnn** [comment]
How to apply the fix on working environment?

**Comment by KaGeN101** [comment]
You can merge that branch #1945 to master locally if you like will do the trick

**Comment by dissnn** [comment]
I meant on working(deployed) Mantl

**Comment by Theaxiom** [comment]
@dissnn You can checkout this branch: https://github.com/mantl/mantl/tree/k8-workaround

**Comment by KaGeN101** [comment]
O yeah I am not sure if the scripts are done in such a way that you can just focus on individual things, but we need to have things like this so we can just restart, update or touch specific components. But to just replace these components you can get the updates k8 yaml and rerun create from it in kubectl and then delete that pod and the RC will recreate it with the new config

**Comment by Theaxiom** [comment]
@KaGeN101 That will come in a future version, when we re-write Mantl using Rust or Go.

**Comment by dissnn** [comment]
@KaGeN101, it works, many thanks man!

**Comment by KaGeN101** [comment]
Fixed in master #1963. Closing the issue.
