### ISSUE TITLE
Upgrading Ansible to latest version

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1972]
2.3 has a feature - new 'order' play level keyword that allows the user to change the order in which Ansible processes hosts when dispatching tasks.

With all the moving parts of Mantl this feature would be nice.

**Comment by bbaassssiiee** [comment]
To my knowledge this should read [2.3](https://github.com/ansible/ansible/tree/v2.3.0.0-1) because 2.8 does not exist in [the Ansible source](https://github.com/ansible/ansible).

**Comment by Theaxiom** [comment]
Thank you @bbaassssiiee I have corrected the OP.

**Comment by Theaxiom** [comment]
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor
