### ISSUE TITLE
Proposed Release Process and Identification

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1980]
# **Release Process**
Stable, Beta, and Alpha

1. The Stable channel should be used by production instances.
2. The Beta channel consists of promoted Alpha releases and should be feature complete. This is the release that should be used for testing.
3. The Alpha channel closely tracks current development work and is released frequently. The newest versions of everything will be available for testing.

Tagged releases are builds of Mantl that pass automated testing. This information is automatically gathered from GitHub. Mantl version numbers are determined by the number of days since the Mantl epoch, Oct 22, 2014. Multiple builds occurring on the same day follow semantic versioning.

_Based on Debian, and CoreOS release process._

**TO IDENTIFY THE RELEASE**
**Method 1**

Every time you login to your Mantl system a "Message of the day" located in /etc/motd is displayed:

Last login: Thu Dec 10 09:05:41 2015 from 10.0.0.8
Mantl stable (835.9.0)
Alternatively, see the content /etc/motd:
cat /etc/motd 
Mantl stable (835.9.0)

**Method 2**

Another and preferred method is to consult the content of /etc/mantl-release file:

cat /etc/mantl-release
NAME=Mantl
ID=coreos
VERSION=835.9.0
VERSION_ID=835.9.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.9.0"
ANSI_COLOR="1;32"
HOME_URL="https:/http://mantl.io/"
BUG_REPORT_URL="https://github.com/mantl/bugs/issues"

**Method 3**

Both methods above only gave us Mantl version number and version ID. To retrieve a Mantl code along with a version number see a content of the /etc/mantl-release file:

cat /etc/mantl-release
DISTRIB_ID=Mantl
DISTRIB_RELEASE=835.9.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="Mantl 835.9.0"

**Comment by Cryptophobia** [comment]
@thomasvincent Looks good! Are we going with all three methods then?

**Comment by dpavlos** [comment]
LGTM. One question though, what's the difference between method 2 and 3? They seem to refer to the same file.

**Comment by Theaxiom** [comment]
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor
