### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by bbaassssiiee** [mantl/mantl#1990]
The rpm name for docker has changed from docker-engine to docker. 

```
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg

```

- Logs from the failing component, if applicable. Might be any of the following:
    virtualbox-iso: ok: [127.0.0.1]
    virtualbox-iso:
    virtualbox-iso: TASK [docker : remove old docker package] **************************************
    virtualbox-iso: ok: [127.0.0.1] => (item=[u'docker', u'docker-common', u'docker-selinux'])
    virtualbox-iso:
    virtualbox-iso: TASK [docker : install docker packages] ****************************************
    virtualbox-iso: failed: [127.0.0.1] (item=[u'docker-engine', u'docker-engine-selinux']) => {"changed": false, "failed": true, "item": ["docker-engine", "docker-engine-selinux"], "msg": "No package matching 'docker-engine' found available, installed or updated", "rc": 126, "results": ["No package matching 'docker-engine' found available, installed or updated"]}
    virtualbox-iso: to retry, use: --limit @/tmp/packer-provisioner-ansible-local/sample.retry

- Changes made to `sample.yml`, if applicable.
None

- Ansible version (`ansible --version`):
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
- Python version (`python --version`):
Python 2.7.13
- Git commit hash or branch:
master
- Cloud Environment:
Vagrant
- Terraform version (`terraform version`):
Terraform v0.9.4

**Comment by Theaxiom** [comment]
Thank you for calling this out @bbaassssiiee 👍

**Comment by thomasvincent** [comment]
https://github.com/mantl/mantl/pull/1999

**Comment by bbaassssiiee** [comment]
Are you alive?
