### ISSUE TITLE
Fixing links in readme 

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1996]
Updating readme with fix's for bad links and instructions on how to keep your fork up to date. 
https://github.com/thomasvincent/mantl/pull/1

**Comment by Theaxiom** [comment]
@thomasvincent Is there a related PR for this issue? Or is this work to be done?

**Comment by thomasvincent** [comment]
my bad 
https://github.com/mantl/mantl/pull/1998

**Comment by Theaxiom** [comment]
Done, thanks!
