### ISSUE TITLE
Move terraform into modules

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#2008]
Right now I feel I am wasting cycles trying to solve #2007,  #2005 
WHat I would propose is we need to refactor the terraform code into modules. This will also help satisfy #2001

Terraform docs on modules:
https://www.terraform.io/docs/modules/usage.html

For example:
./cluster subdirectory. That module has configuration to create a cluster resource, set access and node size rules. The module wraps the bucket and all the other implementation details required to configure a cluster.

We can then define the module multiple times in our configuration by naming each instantiation of the module uniquely, here module "mesos_cluster" and module "kubernetes_cluster", whilst specifying the same module source.

Terraform can retrieve modules from a variety of sources including Git, Mercurial, HTTP, and file paths. The other configurations are parameters to our module. Please fill them in with the proper values. Prior to running any command such as plan with a configuration that uses modules, you'll have to get the modules. In the future we could allow people to do add-ons by retrieving a module remotely. 

For now will stick with the monolithic repo and the modules will be self contained.

**Comment by Theaxiom** [comment]
This will not happen for Mantl 1.x as we are only supporting 1.x as an LTS. There is too much bit-rot to build upon and we have to get away from maintaining a k8s fork. We are currently planning the re-write of Mantl from scratch, you can view the progress and contribute here: https://github.com/cloud-endeavor/endeavor
