### ISSUE TITLE
Replace consul with zetcd

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#2013]
The work has been done to integrate consul with Kubernetes but it isn't apparent if the PR is going to be integrated into Kubernetes. If a configuration is selected to deploy both Mesos and Kubernetes then we will use zetcd instead of consul. 

https://coreos.com/blog/introducing-zetcd
https://github.com/kubernetes/kubernetes/issues/1957
https://github.com/kubernetes/features/issues/172
https://github.com/kubernetes/kubernetes/pull/31622

**Comment by Theaxiom** [comment]
This is not going to happen for 1.x Mantl.
