### ISSUE TITLE
Networking not working properly in Vagrant

### ISSUE THREAD

**Issue by Cryptophobia** [mantl/mantl#2023]
I am getting the below SSH errors when I try to provision a vagrant mantl cluster:

```
GATHERING FACTS *************************************************************** 
ok: [control-01]
fatal: [kubeworker-001] => SSH Error: ssh: connect to host 172.20.10.151 port 22: No route to host
    while connecting to 172.20.10.151:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
fatal: [edge-001] => SSH Error: ssh: connect to host 172.20.10.251 port 22: No route to host
    while connecting to 172.20.10.251:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
fatal: [worker-001] => SSH Error: ssh: connect to host 172.20.10.201 port 22: No route to host
    while connecting to 172.20.10.201:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
```

Any ideas? All the routes and networks in VirtualBox Manager and Vagrant seem to be correctly configured.

Can someone confirm they can get the latest `master` working on Vagrant and what changes if any must be made to get it working?

**Comment by Theaxiom** [comment]
I have not tested the latest `master` in Vagrant recently, I will do that ASAP.

**Comment by dpavlos** [comment]
Can't reproduce this on my local setup. Tested on Vagrant 1.9.3

**Comment by Cryptophobia** [comment]
Hmm, I on Vagrant 1.8.5 and it does not work for me with latest `master`. I wonder what could have broken. Let me investigate the changelog of Vagrant.

**Comment by Cryptophobia** [comment]
Everything works and is back to normal with Vagrant 2.0.0 !!! 

Not sure what broke but updating Vagrant to a later version worked for me! Thanks @dpavlos and @Theaxiom
