### ISSUE TITLE
cert error

### ISSUE THREAD

**Issue by ic3cool** [mantl/mantl#2024]
Getting this when installing with ansible

consul[78605]: ==> Error starting agent: Failed to start Consul server: Failed to read CA file: open /etc/pki/CA/ca.cert: permission denied

-rw-------.  1 root root 1749 Oct  3 13:59 ca.cert

its created with only root access to the CA cert.

**Comment by ic3cool** [comment]
should it not use
/etc/pki/mantl/cert
?

**Comment by ic3cool** [comment]
creating a pull around this.
its fixes my problem
https://github.com/mantl/mantl/pull/2025

**Comment by Theaxiom** [comment]
Thanks!
