### ISSUE TITLE
Openstack .novalocal hardcoded

### ISSUE THREAD

**Issue by tpolekhin** [mantl/mantl#875]
Hello, this hardcode

```
https://github.com/CiscoCloud/microservices-infrastructure/blob/master/plugins/inventory/terraform.py#L252
https://github.com/CiscoCloud/microservices-infrastructure/blob/master/plugins/inventory/terraform.py#L253
```

 negates custom config in `/roles/common/defaults/main.yml`
Spend 2 hours today trying to figure out why my cluster isn't working right

**Comment by ipolyzos** [comment]
The value in defaults can be overridden with playbook vars.  Identified that the issue relies on dnsmasq role and is caused because of NetworkManager restart and the .novalocal setting in /etc/hostname. Setting the /etc/hostname to the proper hostname seems to resolve the issue.

**Comment by tymofii-polekhin** [comment]
any updates on this?
