### ISSUE TITLE
Add options to automate security-setup run

### ISSUE THREAD

**Issue by loshkovskyi** [mantl/mantl#978]
Say I want to automate Mantl deployment in some way. I'll have to have some manual interactions with the `security-setup` script.

Right now, to detach the script from `STDIN` (to which it connects by default), one can use something like this:

```
echo | /usr/bin/python2 security-setup
```

In this case all passwords will be automatically generated and written into `security.yml` (sounds like an undocumented feature).

Should we improve this? In particular, I'd like to have an option to pass passwords to the script either through a command line option or environment variables. Thus, I'll be able to easily automate the script run.

**Comment by siddharthist** [comment]
FYI: when the script is run not attached to a TTY, it automatically generates passwords which can then be read from `security.yml`. I think passing in passwords in the environment sounds like a great idea.

**Comment by sehqlr** [comment]
@loshkovskyi I was looking through unlabeled issues, and I rediscovered this.

How many different passwords do you want to set in the env? Just one, or more?

**Comment by loshkovskyi** [comment]
There might be different use cases, but for me it's enough to set just one: the password for Mantl UI (I think it's `nginx_admin_password` in `security.yml`).
